/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import static GUI.AfficherReservation.AfficherConsultation;
import static GUI.AfficherReservation.AfficherReservatoinEmploye;
import java.time.LocalDate;
import java.time.LocalDateTime;
import javax.swing.JPanel;

/**
 *
 * @author aziz
 */
public class Respo extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Respo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        CardToChangeContent = new javax.swing.JPanel();
        reservationPanel = new javax.swing.JPanel();
        titleLSTReservation = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        reservationContainer = new javax.swing.JPanel();
        consultationPanel = new javax.swing.JPanel();
        titleLSTConsultation = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        consultationContainer = new javax.swing.JPanel();
        feedbackPanel = new javax.swing.JPanel();
        feedbackContainer = new javax.swing.JPanel();
        titleLSTRFeedbacks = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        asideBar = new javax.swing.JPanel();
        reservationBtn = new javax.swing.JButton();
        consultationBtn = new javax.swing.JButton();
        feedbackBtn = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("reservation");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("responsable");
        setBackground(new java.awt.Color(0, 0, 0));

        CardToChangeContent.setLayout(new java.awt.CardLayout());

        reservationPanel.setLayout(new java.awt.BorderLayout());

        titleLSTReservation.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("La liste de RESERVATIONS");

        javax.swing.GroupLayout titleLSTReservationLayout = new javax.swing.GroupLayout(titleLSTReservation);
        titleLSTReservation.setLayout(titleLSTReservationLayout);
        titleLSTReservationLayout.setHorizontalGroup(
            titleLSTReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLSTReservationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titleLSTReservationLayout.setVerticalGroup(
            titleLSTReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLSTReservationLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        reservationPanel.add(titleLSTReservation, java.awt.BorderLayout.PAGE_START);

        reservationContainer.setBackground(new java.awt.Color(255, 255, 204));
        reservationContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        reservationContainer.setLayout(new java.awt.GridLayout(14, 2, 20, 20));
        jScrollPane3.setViewportView(reservationContainer);

        reservationPanel.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        CardToChangeContent.add(reservationPanel, "card3");

        consultationPanel.setBackground(new java.awt.Color(204, 255, 204));
        consultationPanel.setLayout(new java.awt.BorderLayout());

        titleLSTConsultation.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("La liste de CONSULTATIONS");

        javax.swing.GroupLayout titleLSTConsultationLayout = new javax.swing.GroupLayout(titleLSTConsultation);
        titleLSTConsultation.setLayout(titleLSTConsultationLayout);
        titleLSTConsultationLayout.setHorizontalGroup(
            titleLSTConsultationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLSTConsultationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        titleLSTConsultationLayout.setVerticalGroup(
            titleLSTConsultationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLSTConsultationLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        consultationPanel.add(titleLSTConsultation, java.awt.BorderLayout.PAGE_START);

        consultationContainer.setBackground(new java.awt.Color(255, 255, 204));
        consultationContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        consultationContainer.setLayout(new java.awt.GridLayout(14, 2, 20, 20));
        jScrollPane2.setViewportView(consultationContainer);

        consultationPanel.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        CardToChangeContent.add(consultationPanel, "card3");

        feedbackPanel.setBackground(new java.awt.Color(204, 255, 204));
        feedbackPanel.setLayout(new java.awt.BorderLayout());

        feedbackContainer.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout feedbackContainerLayout = new javax.swing.GroupLayout(feedbackContainer);
        feedbackContainer.setLayout(feedbackContainerLayout);
        feedbackContainerLayout.setHorizontalGroup(
            feedbackContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        feedbackContainerLayout.setVerticalGroup(
            feedbackContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        feedbackPanel.add(feedbackContainer, java.awt.BorderLayout.CENTER);

        titleLSTRFeedbacks.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 3, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setText("La liste de FEEDBACKS");

        javax.swing.GroupLayout titleLSTRFeedbacksLayout = new javax.swing.GroupLayout(titleLSTRFeedbacks);
        titleLSTRFeedbacks.setLayout(titleLSTRFeedbacksLayout);
        titleLSTRFeedbacksLayout.setHorizontalGroup(
            titleLSTRFeedbacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLSTRFeedbacksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titleLSTRFeedbacksLayout.setVerticalGroup(
            titleLSTRFeedbacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLSTRFeedbacksLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        feedbackPanel.add(titleLSTRFeedbacks, java.awt.BorderLayout.PAGE_START);

        CardToChangeContent.add(feedbackPanel, "card3");

        asideBar.setBackground(new java.awt.Color(255, 255, 255));

        reservationBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reservationBtn.setText("RESERVATION");
        reservationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationBtnActionPerformed(evt);
            }
        });

        consultationBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        consultationBtn.setText("CONSULTATIONS");
        consultationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultationBtnActionPerformed(evt);
            }
        });

        feedbackBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        feedbackBtn.setText("FEEDBACKS");
        feedbackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout asideBarLayout = new javax.swing.GroupLayout(asideBar);
        asideBar.setLayout(asideBarLayout);
        asideBarLayout.setHorizontalGroup(
            asideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(asideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reservationBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consultationBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(feedbackBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        asideBarLayout.setVerticalGroup(
            asideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asideBarLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(reservationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(consultationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(feedbackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(asideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CardToChangeContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(asideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CardToChangeContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    //RESFRESH BUTTON
    private static boolean reservationClicked = false; 
    private static boolean consultatoinClicked = false; 
    
    
    //STATE -----------------------------------------------  
    Employee[] employees ={
    new Employee(1, "Smith", "John", "médical", 5, "Cardiology"),
    new Employee(2, "Johnson", "Emily", "paramédical", 3, "Physical Therapy"),
    new Employee(3, "Davis", "Michael", "médical", 8, "Pediatrics"),
    new Employee(4, "علي", "محمد", "paramédical", 2, "التمريض"),
    new Employee(5, "خالد", "أمير", "médical", 6, "الطب العام"),
    new Employee(6, "أحمد", "عبدالله", "paramédical", 4, "العلاج الطبيعي"),
    new Employee(7, "مريم", "نور", "médical", 7, "الأطفال"),
    new Employee(7, "مريم", "نور", "médical", 7, "الأطفال"),
    new Employee(7, "مريم", "نور", "médical", 7, "الأطفال"),
    new Employee(7, "مريم", "نور", "médical", 7, "الأطفال"),
    new Employee(7, "مريم", "نور", "médical", 7, "الأطفال"),
    new Employee(7, "مريم", "نور", "médical", 7, "الأطفال"),
    new Employee(7, "مريم", "نور", "médical", 7, "الأطفال"),
    new Employee(7, "مريم", "نور", "médical", 7, "الأطفال"),
    new Employee(7, "مريم", "نور", "médical", 7, "الأطفال"),
    new Employee(7, "مريم", "نور", "médical", 7, "الأطفال"),
};

    

        // Sample data for reservations
        LocalDateTime now = LocalDateTime.now();
        LocalDate today = LocalDate.now();
        int nssPatient = 123456789;
        int codeEmploye = 987654321;

        // Initialize Reservation objects and add them to the array
        Reservation[] reservations = {
new Reservation(1, now, today, "médicale", "injection", "Sample desc 1", nssPatient, codeEmploye),
new Reservation(2, now, today, "paramédicale", "changement_pansements", "Sample desc 2", nssPatient, codeEmploye),
new Reservation(3, now, today, "médicale", "prise_tension", "Sample desc 3", nssPatient, codeEmploye),
new Reservation(4, now, today, "paramédicale", "consultation", "Sample desc 4", nssPatient, codeEmploye),
new Reservation(5, now, today, "médicale", "injection", "Sample desc 5", nssPatient, codeEmploye),
new Reservation(6, now, today, "paramédicale", "changement_pansements", "Sample desc 6", nssPatient, codeEmploye),
new Reservation(7, now, today, "médicale", "prise_tension", "Sample desc 7", nssPatient, codeEmploye),
new Reservation(8, now, today, "paramédicale", "consultation", "Sample desc 8", nssPatient, codeEmploye),
new Reservation(9, now, today, "médicale", "injection", "Sample desc 9", nssPatient, codeEmploye),
new Reservation(10, now, today, "paramédicale", "changement_pansements", "Sample desc 10", nssPatient, codeEmploye),
};

    //END OF STATE ----------------------------------------
    
    private void reservationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationBtnActionPerformed
        // TODO add your handling code here:
        consultationPanel.setVisible(false);
        feedbackPanel.setVisible(false);
        reservationPanel.setVisible(true);
        jScrollPane3.revalidate();
        jScrollPane3.repaint();
        reservationPanel.revalidate();
        reservationPanel.repaint();
        
        if(! reservationClicked){
            AfficherReservatoinEmploye(reservationContainer,reservations);
            reservationClicked = true; 
        
        }
    }//GEN-LAST:event_reservationBtnActionPerformed


    
    private void consultationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultationBtnActionPerformed
        // TODO add your handling code here:
        
        consultationPanel.setVisible(true);
        jScrollPane2.revalidate();
        jScrollPane2.repaint();
        consultationPanel.revalidate();
        consultationPanel.repaint();
        feedbackPanel.setVisible(false);
        reservationPanel.setVisible(false);
        if (! consultatoinClicked){
            System.out.println("GUI.Respo.consultationBtnActionPerformed() 55555555555");
            AfficherConsultation(consultationContainer, employees);
            consultatoinClicked = true; 
        }

    }//GEN-LAST:event_consultationBtnActionPerformed

    private void feedbackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackBtnActionPerformed
        // TODO add your handling code here:
        consultationPanel.setVisible(false);
        feedbackPanel.setVisible(true);
        reservationPanel.setVisible(false);
    }//GEN-LAST:event_feedbackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Respo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Respo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Respo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Respo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Respo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardToChangeContent;
    private javax.swing.JPanel asideBar;
    private javax.swing.JButton consultationBtn;
    private javax.swing.JPanel consultationContainer;
    private javax.swing.JPanel consultationPanel;
    private javax.swing.JButton feedbackBtn;
    private javax.swing.JPanel feedbackContainer;
    private javax.swing.JPanel feedbackPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton reservationBtn;
    private javax.swing.JPanel reservationContainer;
    private javax.swing.JPanel reservationPanel;
    private javax.swing.JPanel titleLSTConsultation;
    private javax.swing.JPanel titleLSTRFeedbacks;
    private javax.swing.JPanel titleLSTReservation;
    // End of variables declaration//GEN-END:variables
}
